TEXT_IDX = 1
SENDER_INFO_IDX = 2
TIMESTAMP_IDX = 9
MEDAL_INFO_IDX = 3
SENDER_UID_IDX = 0
SENDER_USERNAME_IDX = 1
MEDAL_LEVEL_IDX = 0
MEDAL_NAME_IDX = 1
MEDAL_USERNAME_IDX = 2
MEDAL_ROOMID_IDX = 3
MEDAL_STREAMERUID_IDX = -1
MSG_TYPE_IDX = 12  # event["data"]["info"][0][MSG_TYPE_IDX] text:0 ; emoticon:1
TEXT_TYPE = 0
EMOTICON_TYPE = 1
LIVE_STATUS_STREAMING = 1
DM_INTERACTION_ONGOING = 4
DM_INTERACTION_END = 5

'''
For details, see https://github.com/TZFC/BiliLiveManager/wiki/All-non-standard-events 
'''
event_types = {'ANCHOR_HELPER_DANMU', 'ANCHOR_LOT_AWARD', 'ANCHOR_LOT_CHECKSTATUS', 'ANCHOR_LOT_END',
               'ANCHOR_LOT_START', 'AREA_RANK_CHANGED', 'BENEFIT_CARD_CLEAN', 'CARD_MSG', 'CHANGE_ROOM_INFO',
               'COLLECTION_PRAISE_STATUS', 'COLLECTION_PRAISE_UPDATE_PROCESS', 'COMBO_SEND', 'COMMON_NOTICE_DANMAKU',
               'CONFIRM_AUTO_FOLLOW', 'CUSTOM_NOTICE_CARD', 'CUT_OFF', 'DANMU_AGGREGATION', 'DANMU_MSG',
               'DM_INTERACTION', 'ENTRY_EFFECT', 'ENTRY_EFFECT_MUST_RECEIVE', 'FULL_SCREEN_SPECIAL_EFFECT',
               'GIFT_BOARD_RED_DOT', 'GIFT_PANEL_PLAN', 'GIFT_STAR_PROCESS', 'GOTO_BUY_FLOW', 'GUARD_BENEFIT_RECEIVE',
               'GUARD_BUY', 'GUARD_HONOR_THOUSAND', 'INTERACT_WORD', 'LIKE_GUIDE_USER', 'LIKE_INFO_V3_CLICK',
               'LIKE_INFO_V3_NOTICE', 'LIKE_INFO_V3_UPDATE', 'LITTLE_MESSAGE_BOX', 'LITTLE_TIPS', 'LIVE',
               'LIVE_INTERACT_GAME_STATE_CHANGE', 'LIVE_OPEN_PLATFORM_GAME', 'LIVE_PANEL_CHANGE_CONTENT',
               'MESSAGEBOX_USER_GAIN_MEDAL', 'MESSAGEBOX_USER_MEDAL_CHANGE', 'NOTICE_MSG', 'ONLINE_RANK_COUNT',
               'ONLINE_RANK_TOP3', 'ONLINE_RANK_V2', 'PK_BATTLE_END', 'PK_BATTLE_FINAL_PROCESS', 'PK_BATTLE_PRE',
               'PK_BATTLE_PRE_NEW', 'PK_BATTLE_PROCESS', 'PK_BATTLE_PROCESS_NEW', 'PK_BATTLE_RANK_CHANGE',
               'PK_BATTLE_SETTLE', 'PK_BATTLE_SETTLE_USER', 'PK_BATTLE_SETTLE_V2', 'PK_BATTLE_START',
               'PK_BATTLE_START_NEW', 'PLAYTOGETHER_ICON_CHANGE', 'POPULARITY_RED_POCKET_NEW',
               'POPULARITY_RED_POCKET_START', 'POPULARITY_RED_POCKET_V2_NEW', 'POPULARITY_RED_POCKET_V2_START',
               'POPULARITY_RED_POCKET_V2_WINNER_LIST', 'POPULARITY_RED_POCKET_WINNER_LIST', 'POPULAR_RANK_CHANGED',
               'POPULAR_RANK_GUIDE_CARD', 'PREPARING', 'RECOMMEND_CARD', 'RING_STATUS_CHANGE', 'RING_STATUS_CHANGE_V2',
               'ROOM_ADMINS', 'ROOM_BLOCK_MSG', 'ROOM_CHANGE', 'ROOM_CONTENT_AUDIT_REPORT', 'ROOM_LOCK',
               'ROOM_REAL_TIME_MESSAGE_UPDATE', 'ROOM_SKIN_MSG', 'SELECTED_GOODS_INFO', 'SEND_GIFT',
               'SHOPPING_BUBBLES_STYLE', 'SHOPPING_CART_SHOW', 'SHOPPING_EXPLAIN_CARD', 'STOP_LIVE_ROOM_LIST',
               'SUPER_CHAT_ENTRANCE', 'SUPER_CHAT_MESSAGE', 'SUPER_CHAT_MESSAGE_DELETE', 'SUPER_CHAT_MESSAGE_JPN',
               'SYS_MSG', 'TRADING_SCORE', 'USER_INFO_UPDATE', 'USER_PANEL_RED_ALARM', 'USER_TOAST_MSG',
               'VERIFICATION_SUCCESSFUL', 'VIEW', 'WARNING', 'WATCHED_CHANGE', 'WIDGET_BANNER',
               'WIDGET_GIFT_STAR_PROCESS', 'room_admin_entrance'}
